---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/merchant":
    post:
      summary: Register merchant and wallet
      tags:
      - Merchants
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 21
                    legal_name: Loja Exemplo LTDA
                    document: '01119623154'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '409':
          description: Conflict
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Merchant already exists
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      legal_name:
                      - can't be blank
                      document:
                      - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant:
                  type: object
                  properties:
                    legal_name:
                      type: string
                    document:
                      type: string
                  required:
                  - legal_name
                  - document
              required:
              - merchant
    get:
      summary: Get my merchant and wallet
      tags:
      - Merchants
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 23
                    legal_name: Brown and Sons
                    document: '07852968597'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 1000
                      pending_balance_cents: 500
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Not Found
    patch:
      summary: Update my merchant
      tags:
      - Merchants
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 24
                    legal_name: Novo Nome
                    document: '00924699140'
                    status: active
                    account:
                      currency: BRL
                      available_balance_cents: 0
                      pending_balance_cents: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant:
                  type: object
                  properties:
                    legal_name:
                      type: string
              required:
              - merchant
  "/api/v1/me":
    get:
      summary: Get my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 278
                    cpf: '05289757490'
                    email: rickie@blick.test
                    name: Elvie Bauch
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
    patch:
      summary: Update my profile information
      tags:
      - Users
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    name: Novo Nome
                    email: taylor_rolfson@oberbrunner.test
                    cpf: '02797110269'
                    id: 279
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - is not a valid address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
              required:
              - user
    delete:
      summary: Delete my account
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
  "/api/v1/register":
    post:
      summary: Create a new user account
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyODIsImV4cCI6MTc4NTg0NTE4MH0.iOEcJMXHJ0F8yAhMmuYgOIeqakNA8jg4w-MhuOTiwYU
                    refresh_token: HlaY1co3EQDQyziBFSyODAiP4Mnbqa-1mDR12UqjWK8
                    user:
                      id: 282
                      cpf: '07292821987'
                      email: valentin@blanda.test
                      name: Novo Usuario
        '422':
          description: Unprocessable Content
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      email:
                      - has already been taken
                      cpf:
                      - has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    name:
                      type: string
                    cpf:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - name
                  - cpf
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/login":
    post:
      summary: Authenticate user and return token
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyODQsImV4cCI6MTc4NTg0NTE4MH0.xdK6NYZH62lOVqmiyOSgvN1M6uzCeNtpVm_4xBiSrvs
                    refresh_token: VuNLNfBbOgGekG7zwXuqwdgooa3B2RgqCzGeJeuz4U0
                    user:
                      id: 284
                      cpf: '08458777550'
                      email: arlen.waters@white.test
                      name: Vanna Bradtke
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/v1/refresh":
    post:
      summary: Refresh access and refresh tokens
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyODYsImV4cCI6MTc4NTg0NTE4MH0.cbMD6yGcKbIzncp8WeYnhCweKYaNx9Pv0dkhptmy77Q
                    refresh_token: tcVa7h9pXhYwTYiMJLuxuThfJXK1S0ujZ5hAlpeW760
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
  "/api/v1/logout":
    delete:
      summary: Logout current user
      tags:
      - Users
      security:
      - BearerAuth: []
      parameters: []
      responses:
        '204':
          description: No Content
          content:
            application/json:
              examples:
                example:
                  value: ''
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example:
                  value:
                    error: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      in: header
